export const CalendarConsts = {
    navigateConstants: {
        PREVIOUS: "PREV",
        NEXT: "NEXT",
        TODAY: "TODAY",
        DATE: "DATE",
    },
    views: {
        TODAY: "today",
        MONTH: "month",
        WEEK: "week",
        WORK_WEEK: "work_week",
        DAY: "day",
        AGENDA: "agenda",
    },
    messages: {
        date: "Date",
        time: "Time",
        event: "Event",
        allDay: "All Day",
        week: "Week",
        work_week: "Work Week",
        day: "Day",
        month: "Month",
        previous: "Back",
        next: "Next",
        yesterday: "Yesterday",
        tomorrow: "Tomorrow",
        today: "Today",
        agenda: "Agenda",
    },
};
